---
- hosts: all
  tasks:
   - name: test module
     ansible.windows.win_powershell:
       script: |
         get-website | ForEach-Object {$env:computername + " | " + $_.Name + " | " + $_.PhysicalPath + " | " + $_.state}
      
   - debug:
        var: script_result.stdout_lines
