---
- hosts: all
  tasks:
   - name: test module
     ansible.windows.win_powershell:
       script: |
         $out = get-website | ForEach-Object {$env:computername + " | " + $_.Name + " | " + $_.PhysicalPath + " | " + $_.state}
         Write-Output $out
