---
- hosts: all
  tasks:
   - name: test module
     ansible.windows.win_powershell:
       script: |
         get-website | ForEach-Object {$env:computername + " | " + $_.Name + " | " + $_.PhysicalPath + " | " + $_.state}

   - name: Retrieve the input based on stdin
   ansible.windows.win_shell: '$string = [Console]::In.ReadToEnd(); Write-Output $string.Trim()'
   args:
     stdin: Input message
