---
- hosts: all
  tasks:
   - name: test module
     ansible.windows.win_shell: |
         get-website | ForEach-Object {$env:computername + " | " + $_.Name + " | " + $_.PhysicalPath + " | " + $_.state}
     register: hello
     
   - name: Retrieve the input based on stdin
     ansible.windows.win_shell: '$string = [Console]::In.ReadToEnd(); Write-Output $string.Trim()'
     args:
       stdin: Input message
